version: '3'


services:
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: asset_db
      DATABASE_HOST: localhost
      PGDATA: /data/postgres
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
       - ./resources/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "5432:5432"


volumes:
  postgres-db:
    driver: local
